name: ubuntu-gcc13

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Installation
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev p7zip gobjc g++-13 wget sudo libcurl4-openssl-dev libnss3 nss-plugin-pem ca-certificates
          wget https://github.com/lwthiker/curl-impersonate/releases/download/v0.5.4/libcurl-impersonate-v0.5.4.x86_64-linux-gnu.tar.gz
          sudo mv libcurl-impersonate-v0.5.4.x86_64-linux-gnu.tar.gz /usr/lib64
          cd /usr/lib64
          sudo tar -xvf libcurl-impersonate-v0.5.4.x86_64-linux-gnu.tar.gz
          cd -
          wget https://github.com/xmake-io/xmake/releases/download/v2.8.2/xmake-v2.8.2.xz.run
          chmod 777 xmake-v2.8.2.xz.run
          ./xmake-v2.8.2.xz.run > a.txt

      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          export XMAKE_ROOT="y"
          source ~/.xmake/profile
          g++-13 -v
          export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH
          export LIBRARY_PATH=/usr/lib64:$LIBRARY_PATH
          export CXX=g++-13
          export CC=gcc-13
          xmake build -y
          xmake install -o .
          ldd ./bin/cpp-freegpt-webui

      - name: Docker login for dev
        if: github.ref_name == 'dev' && github.repository_owner == 'fantasy-peak'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker login for main
        if: github.ref_name == 'main' && github.repository_owner == 'fantasy-peak'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image and push to dev
        if: github.ref_name == 'dev' && github.repository_owner == 'fantasy-peak'
        run: |
          docker run --rm --privileged tonistiigi/binfmt:latest --install all
          docker buildx create --name fantasy-peak-builder
          docker buildx use fantasy-peak-builder
          docker buildx inspect --bootstrap fantasy-peak-builder
          docker buildx ls
          docker buildx build --platform linux/arm64,linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/freegpt:dev . --push
          cd tools
          docker buildx build --platform linux/arm64,linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/freegpt-zeus:dev . --push
          cd ..

      - name: Build the Docker image and push to main
        if: github.ref_name == 'main' && github.repository_owner == 'fantasy-peak'
        run: |
          docker run --rm --privileged tonistiigi/binfmt:latest --install all
          docker buildx create --name fantasy-peak-builder
          docker buildx use fantasy-peak-builder
          docker buildx inspect --bootstrap fantasy-peak-builder
          docker buildx ls
          docker buildx build --platform linux/arm64,linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/freegpt:latest . --push
          cd tools
          docker buildx build --platform linux/arm64,linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/freegpt-zeus:latest . --push
          cd ..
